### ISSUE TITLE
'host p("etcd.dns_health_check_host")' needs to look at A records only

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/etcd-release#10]
For the diego-database role, etcd_ctl fails with this error message:
```
Host consul.nif not found: 3(NXDOMAIN)
Host consul.nif not found: 3(NXDOMAIN)
DNS is not up
```
root@api:/# host -t A consul.hcf
consul.nif has address 172.20.10.6

**Comment by Amit-PivotalLabs** [comment]
Closing in favour of your PR: https://github.com/cloudfoundry-incubator/etcd-release/pull/11

**Comment by ericpromislow** [comment]
develop PR in https://github.com/cloudfoundry-incubator/etcd-release/pull/12
