### ISSUE TITLE
etcd_metrics_server_ctl points to `common`, not etcd-common

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry-incubator/etcd-release#14]
Line 7 in [etcd_metrics_server_ctl](https://github.com/cloudfoundry-incubator/etcd-release/blob/6e7e9be56277205f59a855ba0a26fd87845af1ee/jobs/etcd_metrics_server/templates/etcd_metrics_server_ctl.erb#L7) points to `/var/vcap/packages/common/utils.sh`. The `common` package is not present in either `etcd` or `etcd_metrics_server` releases. Neverteless, there's `utils.sh` present in `/var/vcap/packages/etcd-common/utils.sh`. Maybe the ctl script should use that script, instead the one from `common` package...

**Comment by Amit-PivotalLabs** [comment]
Thanks for catching this.  Fixed here: https://github.com/cloudfoundry-incubator/etcd-release/commit/001da10b0d5a26de608368652aeb70e04896883b
