### ISSUE TITLE
Release notes please?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/etcd-release#16]
Could it be possible to get release notes for each new version? We're integrating this release into other projects than cf-release (which I believe was the intent of extracting etcd from cf-release).

**Comment by Amit-PivotalLabs** [comment]
Will do, going forward.

**Comment by drnic** [comment]
:heart:

**Comment by Amit-PivotalLabs** [comment]
In the mean time, any specific questions about diff between whatever release you were on and the current release?

**Comment by drnic** [comment]
Nope - currently I am blindly upgrading as the versions roll out via CI. Realized there could be "bad things happen" if I keep doing that :)
