### ISSUE TITLE
bash syntax errors in the ctl scripts

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry-incubator/etcd-release#17]
Looks like a bash syntax error made it into the ctl helper script:

1. https://github.com/cloudfoundry-incubator/etcd-release/blob/master/jobs/etcd/templates/etcd_bosh_utils.sh.erb#L51

**Comment by ryanmoran** [comment]
Fixed here https://github.com/cloudfoundry-incubator/etcd-release/commit/a240183ec876c48359c833d088f698e28ce5c88f
