### ISSUE TITLE
scripts/generate-etcd-certs uses incorrect domain

### ISSUE THREAD

**Issue by swetharepakula** [cloudfoundry-incubator/etcd-release#21]
The script uses the domain, "etcd.service.consul", it should be "etcd.service.cf.internal".

Thanks,
@swetharepakula & @DanLavine

**Comment by christianang** [comment]
Hi @swetharepakula,

I have updated the script to use cf.internal.

Thanks for the feedback.

-Christian

**Comment by swetharepakula** [comment]
Thanks!
