### ISSUE TITLE
Bosh 2.0 style

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-incubator/etcd-release#34]
Hi,

Could be nice if this release start to implement bosh 2.0 ish style, especially links and so on which ease the use of this release in other deployment / release.

Thanks

**Comment by evanfarrar** [comment]
Hi @shinji62 

This is something we have in our icebox currently. Our team is still in the process of adding links to consul, but we can look at prioritizing links for etcd after that.

https://www.pivotaltracker.com/story/show/132714955

**Comment by drnic** [comment]
@shinji62 @evanfarrar perhaps try out #38

**Comment by shinji62** [comment]
Thanks @drnic will check that.

**Comment by christianang** [comment]
FYI. We have just cut [etcd-release v100](https://github.com/cloudfoundry-incubator/etcd-release/tree/v100) which has @drnic's links PR.

**Comment by drnic** [comment]
Thanks!

________________________________
