### ISSUE TITLE
[Feature] ZETCD

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-incubator/etcd-release#39]
Hi,

i am wondering if you could be interested in [ZETCD](https://github.com/coreos/zetcd) to enhance this bosh release to support Zookeeper through etcd.

Could be useful for many system which only support Zookeeper protocol.

I am willing to make the PR.

Thanks.

**Comment by evanfarrar** [comment]
@shinji62 we have been slowly reducing our integrations with ETCD over time, so supporting a new frontend to ETCD would be a step in the other direction.

This is a distribution of ETCD meant to be bundled into the same deployment as Cloud Foundry to serve as the database of a few CF components (well, as of now only one component). It is not intended for a general usage as we do some things which might surprise a user (such as removing data to resolve conflicts, at times).

Perhaps there is a need for a general purpose etcd BOSH release, much like cloudfoundry-community/consul-boshrelease is a more general purpose consul release than cloudfoundry-incubator/consul-release. But it would not be maintained as a core Cloud Foundry project unless it was part of the runtime.

**Comment by shinji62** [comment]
Ok, I will create my own bosh release.
Thanks
