### ISSUE TITLE
Use of etcd-release as key-value store and locking

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry-incubator/etcd-release#49]
Hi,

We were currently evaluating ETCD to be used as part of Service Fabrik (https://github.com/cloudfoundry-incubator/service-fabrik-broker) mainly for key value store and for distributed locking.
       I heard there is some issue for which CF is moving away from ETCD release, was wondering if I can get details around that and if you can comment whether we can use it for our use-case.

**Comment by genevieve** [comment]
Our issues were mostly about upgrades in the context of bosh. To maintain the cluster, you cannot jump between major/minor versions. You need to upgrade each node in the cluster to the next minor and so on until you reach the version are you are looking for. This would mean having every version of etcd-release necessary to go through each minor and to `bosh deploy` with each one. This would mean multiple deploys and it's something we hoped for a better solution to.

Hope this clarifies it a bit!
