### ISSUE TITLE
version tagging inconsistent with rest of Cloud Foundry

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/etcd-release#7]
With the cf-release, diego-release, and garden-linux-release, the tags for versions are prefixed with "v". For example the latest release would be "v18".

It would be great to have the versioning prefix.

If there is a concourse pipeline this exists on, happy to contribute to it.

**Comment by Amit-PivotalLabs** [comment]
Nice catch @jtarchie 

Should be a simple change, see https://github.com/cloudfoundry/mega-ci/search?utf8=%E2%9C%93&q=tag

Happy to accept a PR!

**Comment by Amit-PivotalLabs** [comment]
Thanks for the PR! Closing this issue.
